title: Jaeyoung's Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

#url: https://long-haul.netlify.app
url: https://rktlskan021.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  github: rktlskan021
  email: rktlskan021@kookmim.ac.kr

google_analytics: "UA-215560049-1"
comment:
    provider: "disqus"
    disqus:
       shortname: "rktlskan021"